### ISSUE TITLE
About using `topic_name` and `subject_name` to answer the questions.

### ISSUE THREAD

**Issue by vlievin** [medmcqa/medmcqa#1]
Hello! Great dataset & paper! I am looking forward to submitting my results! :) 

I have a question regarding using the columns `subject_name` and `topic_name`. I can see that you're not using them in the QA model, however, they provide very useful context to answer the questions and to retrieve documents that are relevant to the question. 

For instance, without using the topic and subject, the question is
```
Chronic urethral obstruction due to benign prismatic hyperplasia can lead to the following change in kidney parenchyma
```

Using the topic and subject, we could use:
```
Topic: anatomy, subject: urinary tract. Chronic urethral obstruction due to benign prismatic hyperplasia can lead to the following change in kidney parenchyma
```

What are your thoughts regarding using these columns, would you consider it valid for a submission? Are these topics and subjects known by the students when participating in the exam?

Another quick question, you mentioned the score for the best students (~90%), what would be the passing score for typical students?

**Comment by monk1337** [comment]
@vlievin Sure, feel free to use the format, it would come under the `with context` benchmark. The passing score for a typical student is 50%
